source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'HelloWorldSwift.xcodeproj'
platform :ios, '8.0'

pod 'AeroGearPushSwift', :git => "https://github.com/cvasilak/aerogear-ios-push.git", :branch => "distrib"
